#!/usr/bin/env bash
#
# ohmyPM 운영 세팅 wizard — 텔레그램 연결 + 부팅 자동실행 등록.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=4

banner "ohmyPM 운영 세팅 — 텔레그램 알림 + 부팅 자동실행"

# ── Stage 1: 텔레그램 봇 생성 · 토큰 ──────────────────────────────────────
stage "텔레그램 봇 생성 · 토큰"
say "폰으로 알림을 받으려면 텔레그램 봇 하나가 필요합니다(무료, 1분)."
open_url "https://t.me/BotFather"
step "열린 BotFather 대화창에 /newbot 을 보냅니다"
step "봇 이름(표시용, 아무거나) → username(반드시 'bot'으로 끝나야 함) 입력"
step "BotFather가 준 토큰(예: 123456789:ABCdef...)을 복사합니다"
ask_secret TELEGRAM_BOT_TOKEN "봇 토큰 붙여넣기:"
write_env TELEGRAM_BOT_TOKEN "$TELEGRAM_BOT_TOKEN"

# ── Stage 2: chat_id 확인 ─────────────────────────────────────────────────
stage "chat_id 확인 (누구에게 보낼지)"
say "봇이 '당신에게' 보내도록 chat_id를 알아냅니다."
step "방금 만든 봇을 텔레그램에서 열고 아무 메시지나 한 번 보내세요 (예: hi)"
pause "메시지 보냈으면 Enter"
open_url "https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/getUpdates"
step "열린 JSON에서  \"chat\":{\"id\": 뒤의 숫자(음수일 수도)를 복사합니다"
note "예: ...\"chat\":{\"id\":123456789,... → 123456789"
ask TELEGRAM_CHAT_ID "chat_id 붙여넣기:"
write_env TELEGRAM_CHAT_ID "$TELEGRAM_CHAT_ID"

# ── Stage 3: 발송 테스트 ──────────────────────────────────────────────────
stage "발송 테스트"
say "실제로 폰에 도착하는지 확인합니다."
if curl -s "https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage" \
      --data-urlencode "chat_id=$TELEGRAM_CHAT_ID" \
      --data-urlencode "text=✅ ohmyPM 연결 완료 — 이제 매일 요약이 여기로 옵니다." \
      | grep -q '"ok":true'; then
  say "폰 텔레그램에 'ohmyPM 연결 완료' 메시지가 왔는지 확인하세요."
else
  warn "발송 실패 — 토큰/chat_id를 다시 확인하세요. 이 wizard를 재실행하면 값이 유지됩니다."
fi
pause "확인했으면 Enter"

# ── Stage 4: 부팅 시 자동 실행 등록 (작업 스케줄러) ──────────────────────
stage "부팅 시 자동 실행 등록"
say "PC 로그인할 때마다 대시보드 서버가 자동으로 켜지게 등록합니다."
say "서버가 켜져 있어야 매일 08:00 자동 스캔 + 텔레그램 요약이 돕니다."
note "등록 대상: scripts\\run_ohmypm.cmd → 로그인 시(onlogon) 실행"
if confirm "지금 작업 스케줄러에 등록할까요?"; then
  if MSYS_NO_PATHCONV=1 schtasks.exe /create /tn "ohmyPM" \
        /tr "C:\\Users\\minhy\\project\\ohmyPM\\scripts\\run_ohmypm.cmd" \
        /sc onlogon /f; then
    say "등록 완료 — 다음 로그인부터 자동 실행됩니다."
    say "지금 바로 켜려면 새 창에서:  scripts\\run_ohmypm.cmd"
  else
    warn "등록 실패 — 관리자 권한이 필요할 수 있습니다."
    note "수동: scripts\\register_task.cmd 를 관리자 권한으로 실행하세요."
    SKIPPED+=("작업 스케줄러 등록 (scripts\\register_task.cmd 관리자 실행)")
  fi
else
  note "나중에 등록하려면: scripts\\register_task.cmd 실행"
  SKIPPED+=("작업 스케줄러 등록")
fi

finish
